### ISSUE TITLE
Integration Tests: manager_tests.go

### ISSUE THREAD

**Issue by stephenrlouie** [sigma-dev/sigma#157]
##### Description

The `tests/integration/manager_tests.go` are all botched. The types system changes effected them, recursive from's need to be fixed and will be in types work. We also do not pass along an output from a plugin definition to the service output. 

In #156I put a `map[string]interface{}` in its place instead. I removed `ActualEquals` and replaced it with `reflect.DeepEquals`. Not sure if that is correct, but I know services and plugins are valid and being added to the system. 

##### Sigma Version

0.1

##### Sigma Configuration

Normal

##### Command line used for generation / environment

`go test -v github.com/sigma-dev/sigma/tests/integration/manager`

##### Suggest a Fix

We need to look into how Inputs and Outputs are handled, everything was being cast into a `[]string` before and #156 began trying to fix it. We fail on validation of those due to the representation of Inputs and Outputs

**Comment by mcaulfield** [comment]
Probably fixed.
