### ISSUE TITLE
Tasker status consistency re: plugin failures (exit codes) 

### ISSUE THREAD

**Issue by meganokeefe** [sigma-dev/sigma#204]
Need to ensure that `tasker.Status` returns the same error for an exit code = 1. 

This will assure plugin authors that if their plugin fails, manager catches that failure the same way across both taskers.

**Comment by mcaulfield** [comment]
Consider putting more structure around the "progress" file to report both running progress as well as errors.

**Comment by adamschaub** [comment]
Fixed as of #295
