### ISSUE TITLE
expose Service.Remove as a readonly variable

### ISSUE THREAD

**Issue by stephenrlouie** [sigma-dev/sigma#205]
##### Description

Serivces have a boolean flag for Removal. It indicates to the manager that the Service should be removed. We do not include this variable in our [swagger doc](https://github.com/sigma-dev/sigma/blob/master/api/v1/gen/v1.yaml#L615-L651). We should expose that value in the API so a UI could display what Services are marked for deletion but have yet to have the Destroy operation run on them.

**Comment by mcaulfield** [comment]
Not an issue.
