### ISSUE TITLE
DB object reference consistency

### ISSUE THREAD

**Issue by stephenrlouie** [sigma-dev/sigma#208]
##### Description

If two objects reference each other, say the `Service.Site` field. Should that value be the `Name` or `ID`. It shouldn't be a problem if you `GetSite` since we try both name and ID. 

But if I want to find all services that refer to my Site, I will have to query on `Service.Site: <ID>` and `Service.Site: <Name>` to be sure I catch everything since we are not strict on what will be stored in those fields.

**Comment by mcaulfield** [comment]
tldr: Switch from using names for references to using IDs everywhere consistently.
