### ISSUE TITLE
Reconnect on RabbitMQ Connection Drop 

### ISSUE THREAD

**Issue by stephenrlouie** [sigma-dev/sigma#225]
##### Description

Sigma should handle the case where the couchbase container is restart or we drop connection for anything. Sigma should re-establish that connection with couchbase

**Comment by stephenrlouie** [comment]
is this also a problem for rabbit?

**Comment by adamschaub** [comment]
Should be a problem for rabbit too. It would be appropriate for the manager to detect a failed connection and attempt to reconnect in it's main event loop

**Comment by meganokeefe** [comment]
Came to the consensus yesterday that this problem needs to be addressed only for Rabbit.
