### ISSUE TITLE
More bad errors

### ISSUE THREAD

**Issue by mikeynap** [sigma-dev/sigma#234]
If I leave sigma running it starts barfing: 
ERRO[2017-07-10T14:22:00-04:00] Unable to get service operation=              error="Object not found" file=manager.go line=538
ERRO[2017-07-10T14:22:00-04:00] Unable to update service operation            error="CAS not found in metadata, please GET before Update" file=manager.go line=544

**Comment by adamschaub** [comment]
@mikeynap Can you elaborate on this more? What configuration where you running it on, how many/what services/how long do you estimate it was running. Any possible computer hibernations in the interim. Need some more details.

**Comment by mcaulfield** [comment]
Probably fixed elsewhere.
