### ISSUE TITLE
Manager fails to run Destroy operations on ServiceDelete 

### ISSUE THREAD

**Issue by meganokeefe** [sigma-dev/sigma#238]
(Tested with multiple plugins) 

I run a plugin, it successfully deploys and statuses. 

Then I delete the service: `curl -X DELETE http://127.0.0.1:24601/v1/services/dittoSvc1` 

Then this happens: 
```
INFO[2017-07-10T16:10:31-04:00] Destroying Service: dittoSvc1                 file=server.go line=744
DEBU[2017-07-10T16:10:31-04:00] Acquired service queue lock                   file="service_provider.go" line=64
DEBU[2017-07-10T16:10:32-04:00] Deleted doc with ID: 9d6d126d-db25-4cf7-85e6-2d584d7fe799 from Bucket: default  file=couchbase.go line=229
ERRO[2017-07-10T16:10:32-04:00] Could not update service "dittoSvc1"          error="Object not found" file=manager.go line=278
```

And the service has been deleted from the DB. Manager isn't getting to the point where it's starting a "destroy" serviceOperation.

**Comment by meganokeefe** [comment]
False alarm, I think my queue got into a weird state- restarting docker + dependencies fixed the problem.

**Comment by adamschaub** [comment]
Me please
