### ISSUE TITLE
Docker Tasker in HA 

### ISSUE THREAD

**Issue by mikeynap** [sigma-dev/sigma#273]
The way we currently handle docker tasks does not allow for multiple sigmas to be run in our defined HA story.

Is the ability to have N sigma instances on different machines that each deploy jobs to their respective dockers something that we want to support?

It would involve possibly marking where a service is being run, and only having the machine that started it handle updating the outputs.

**Comment by mcaulfield** [comment]
Wrong. Use Nomad tasker for HA (or write a K8S tasker).
