### ISSUE TITLE
Nomad functional tests needed

### ISSUE THREAD

**Issue by stephenrlouie** [sigma-dev/sigma#280]
##### Description

`make nomad_integration` ? not always working. sometimes we cannot get Status.

nomad does not report outputs to sigma properly on  the `TestNomad` functional tests

**Comment by mikeynap** [comment]
The make nomad_integration always works locally.
It _NEVER_ works on travis -- the only times it "works" is when travis decides not to run it. 
It's weird, travis occasionally skips `make nomad_integration` test completely...  and when it does skip it, we get a green light (iff it skips it).

**Comment by stephenrlouie** [comment]
I do think it works on travis but its just non-deterministic. https://travis-ci.org/sigma-dev/sigma/builds/258663669

**Comment by stephenrlouie** [comment]
I modified the nomad command. https://travis-ci.org/sigma-dev/sigma/builds/259163945

**Comment by stephenrlouie** [comment]
TODO 
- [ ] Fix nomad functional tests

**Comment by meganokeefe** [comment]
Go mike! https://github.com/sigma-dev/sigma/blob/master/tests/functional/orchestrator/orchestrator.go#L336
