### ISSUE TITLE
Verify NullDB and Couchbase api/server GetServices is working

### ISSUE THREAD

**Issue by vgunning** [sigma-dev/sigma#312]
Verify that the NullDB and Couchbase tests for GetServices actually works

##### Description

A TODO was written wondering if the nulldb and couchbase GetServices was functioning.

##### Sigma Configuration

Run tests with both couchbase and nulldb

**Comment by meganokeefe** [comment]
Is this a duplicate of #316 now?

**Comment by mcaulfield** [comment]
Stale.
