### ISSUE TITLE
// TODO - fix once nullDB query is fixed?

### ISSUE THREAD

**Issue by vgunning** [sigma-dev/sigma#327]
Found in the `TestValidateService` function in the `api/v1/server` folder tests.

##### Description

The database queries should be fixed and functional, meaning that something other than the db queries is causing the old validate tests to fail. After some triage, it appears to be that the validate tests need rewritten because they aren't actually using objects that should be validate in some cases. (Missing site, ...)

##### Suggest a Fix

Rewrite the server/validate tests to test valid and invalid objects.

**Comment by mcaulfield** [comment]
No longer an issue.
