### ISSUE TITLE
Remove confusing language from docs 

### ISSUE THREAD

**Issue by meganokeefe** [sigma-dev/sigma#358]
Plugins, updates, services -- be clear about what is Sigma jargon!

**Comment by adamschaub** [comment]
Better document "required vars" heuristic (i.e. no default, not marked as generated)

**Comment by adamschaub** [comment]
Make sure runtime dependencies are documented (Docker, Couchbase, Rabbit, etc)

**Comment by adamschaub** [comment]
Make sure Plugin developer guide is up to date with important considerations: logging plugin name, understanding plugin requirements (against other plugins), env vars, etc. Ensure plugin development is well defined

**Comment by mcaulfield** [comment]
Redundant with #350
