### ISSUE TITLE
ServiceOperation ID changes when archived

### ISSUE THREAD

**Issue by stephenrlouie** [sigma-dev/sigma#372]
##### Description

When an operation runs we log `Started 'Deploy' Operation 0c932dd3-3fc1-4b0a-932c-d23b809841f1  Service=135c27bc-1527-46de-89a2-118115ef6be7` While the plugin is running it will use the ID `oc932....` as its ID to call the `SIGMA_URL` and hit the `/inputs` `/outputs`. 

Once that operation ends we change the id. https://github.com/sigma-dev/sigma/blob/master/manager/manager.go#L714

IMO: We should keep this ID consistent for debugging purposes. If I see the logs use that service-Id. I want to find that exact operation in the DB. currently you can't know for sure which operation, you have to base it off timestamps. 

Cons: We are exposing the primary key of the object in the DB? risky?

##### Steps to reproduce

Run sigma, added hello-world plugin followed the Service-ID around.

##### Suggest a Fix

Remove the archive generated ID.

**Comment by rfliegerallison** [comment]
This is a non-issue, because while the `<serviceID>-opID` ID changes when archived, the hash of that ID remains unchanged and can be used to track the archived operations during debugging.
