### ISSUE TITLE
Wish List for Plugin Utilities

### ISSUE THREAD

**Issue by adamschaub** [sigma-dev/sigma#378]
Some ideas for utilities that would increase the QoL for plugin writers. 

- [x] Plugin README generator
- [x] Plugin definition to golang struct translator (ask @meganokeefe?)
- [ ] Plugin version mgmt
  - [x] Easily vendor other plugin var definitions into plugin (based on translator above?)
  - [ ] Provide client functions to unmarshal vars into the correct type/version based on metadata

**Comment by rfliegerallison** [comment]
This has been split into several separate issues.
