### ISSUE TITLE
Redundant query functions in DB 

### ISSUE THREAD

**Issue by meganokeefe** [sigma-dev/sigma#379]
Right now all our Query functions take in an empty object of a specific type. But now that `makeQuery` has been consolidated / made more generic, we might be able to get away with a single `db.Query()` function where we pass in a generic type and a set of filters. 

TBD, need to determine if there's a reason it is this way.

**Comment by rfliegerallison** [comment]
After attempting this, it was decided that the `reflect` "magic" required to make a truly generic query function was not worth the extra obfuscation/performance hit that it creates.
