### ISSUE TITLE
Control+C often does not cleanly shutdown sigma

### ISSUE THREAD

**Issue by mikeynap** [sigma-dev/sigma#45]
Input: Ctrl+C
Expected: 
    Clean Exit of Sigma
Actual: 
    ```^CINFO[2017-05-03T19:02:10-04:00] Sigma SIGINT Received. Shutting down...       file=sigma.go line=83
DEBU[2017-05-03T19:02:10-04:00] TCP Listener: accept tcp [::]:2481: use of closed network connection  file=server.go line=62
INFO[2017-05-03T19:02:10-04:00] Quitting Sigma APIServer                      file=server.go line=73```

And then it hangs and requires a SIGKILL.

**Comment by adamschaub** [comment]
Need to figure out how to reproduce this

**Comment by mikeynap** [comment]
For me, after a bunch of tests are run, my docker freezes up on start... so I get it a lot. 
Idk how you'd re-create it if yours functions perfectly. 

Making the Tasker.Run() async from manager would fix it.

**Comment by mcaulfield** [comment]
Probably fixed with async manager / message queue.
