### ISSUE TITLE
DB By ID / Name support

### ISSUE THREAD

**Issue by stephenrlouie** [sigma-dev/sigma#54]
##### Description

Need to be more specific in how we handle taking a Name and getting an ID. It is possible that two items of the same type could share a name. We just take the first return and use that? I don't think thats right, maybe we have to return an error since we can't know which name you meant.

##### Related issues

https://github.com/sigma-dev/sigma/blob/sites-api/database/couchbase.go#L206

**Comment by meganokeefe** [comment]
Duplicate of #107
