### ISSUE TITLE
API Error Code Specificity

### ISSUE THREAD

**Issue by stephenrlouie** [sigma-dev/sigma#59]
##### Description

Many of the site error codes can be more specific once #46 closes. For example, we return a 404 whenever a Get fails, but that Get could fail for other reasons outside of SiteNotFound.

##### Related issues

Depends on: #46

##### Suggest a Fix

Leverage the fix of #46 to be more specific in error returns so the user has relevant info when an error occurs.

**Comment by mcaulfield** [comment]
Fix with #124
