### ISSUE TITLE
Enabled should be set to true by default

### ISSUE THREAD

**Issue by mikeynap** [sigma-dev/sigma#91]
I feel like the cases where one would want a service to be enabled upon adding is more common than the current "enabled: false" default. 

Adding a service already depends on other services being ready, I think it makes sense to have them enabled unless specifically told NOT to be enabled. 

Just a thought.

(if we decide this is stupid and I should shut up, maybe a /v1/servies/{Sid}/enable would be a convenient endpoint).

**Comment by mcaulfield** [comment]
Yes.
