### ISSUE TITLE
Revamp plugin type handling

### ISSUE THREAD

**Issue by adamschaub** [sigma-dev/sigma#98]
Master issue for implementing more complex types per plugin.

What need do:
- [x] Add types to Plugin in model
- [x] Add types to Plugin in API
- [x] Update Plugin/Service inputs/outputs to be map of var-name -> var-info
- [x] Convert values to generic `interface{}`
- [x] Allow nested object/list types (i.e. list of objects that have lists of objects, etc)
- [ ] Add constraint processing for types
 - [x] Reflection on provided Plugin/Service values to ensure specified type matches actual value
- [x] Basic conversion to/from basic types. I.e. if a field specifies string and is given an int, convert the int to a string
- [x] Syntax to use specific vars for a nested object field
- [x] Add generic `validation` or `accept` to types (and inputs?)
- [x] Inputs optional

Separate into a few PRs:
- [x] Update model/api definitions (use maps instead of lists, use interface for values). Everything works the same otherwise. No strong vetting of types, etc
- [x] Type conversion functions (between all basic types + lists) + vet types/attempt conversion during processing
- [ ] Validation using contraints (add to processing). Update model/api accordingly. Just enum to start

**Comment by mcaulfield** [comment]
Move on with your life.
